### ISSUE TITLE
simple_cylinder3.xacro

### ISSUE THREAD

**Issue by sssmile2020** [webvenky/simple-airplane#4]
Hi. 

Your work is excellent! 

I want to try it. But maybe i need some help. 
I have met some problem when i roslaunch the .launch file. 
I cannot find "simple_cylinder3.xacro" in your urdf.
Is there something wrong with me?

I hope i could keep learning from you.
Thanks for your patience.

**Comment by webvenky** [comment]
Sorry for not checking my github. Added the missing file to the repository.
